[[repo]]
pattern = "*"
branches = ["v0.0", "v1.0", "v2.0"]

[[repo]]
name = "Anymoid/Boid"
description = """
Boid package base. A foundational package that defines shared abstractions for a general-use robotics framework. It serves as a base for other repositories, facilitating inheritance and automatic updates for data model changes. Designed to be versatile and adaptable, it underpins a broad range of robotics applications without specific technological constraints."""
branches = ["v0.0", "v1.0", "v2.0"]

[[repo]]
name = "Anymoid/Anymoid"
description = """
Anymoid package base. Advanced robotic framework featuring a bidirectional modality broker and cloud control system. Anymoids are equipped for complex operations, with subrepos including a Next.js frontend, robot clients for RPi and ESP32, and a Docker-based agent server for streaming modalities. The application server manages orchestration, authentication, storage, billing, and other essential functions. Suitable for a wide array of simple robots."""
clone = "Anymoid/Boid"
[[repo.subrepos]]
path = "frontend/website"
name = "Anymoid/website"
[[repo.subrepos]]
path = "robot/robot_rpi"
name = "Anymoid/robot_rpi"
[[repo.subrepos]]
path = "robot/robot_esp32"
name = "Anymoid/robot_esp32"
[[repo.subrepos]]
path = "server/agent_server"
name = "Anymoid/agent_server"
[[repo.subrepos]]
path = "server/application_server"
name = "Anymoid/application_server"

[[repo]]
name = "AnimoidAI/Animoid"
description = """
A streamlined variant of Anymoid, tailored for a specific set of servers, mics, cameras, and speakers. The Animoid focuses on simplicity, with a custom frontend offering an intuitive user experience. Designed for ease of use, it caters to specialized robotic applications with constrained UX requirements."""
clone = "Anymoid/Anymoid"
[[repo.subrepos]]
path = "frontend/myAnimoid"
name = "AnimoidAI/myAnimoid"

[[repo]]
name = "AnimoidAI/GoodBoi"
description = """
A specialized Animoid configured as an inflatable dog. GoodBoi builds upon the Animoid base, adding specific configurations, hardware BOMs, and design sheets tailored for canine form and functionality."""
clone = "AnimoidAI/Animoid"

[[repo]]
name = "Anymoid/CyBoid"
description = """
A revolutionary wearable device capable of reading brain waves and environmental inputs. Designed for broad mammalian compatibility, CyBoid connects humans and animals to a vast 'Boidnet', facilitating unprecedented interspecies communication and interaction."""
clone = "Anymoid/Anymoid"

[[repo]]
name = "Anymoid/HomeBoi"
description = """
A sophisticated homepod, wall-mounted or desktop, featuring camera and voice interface, uniquely designed for seamless integration with the broader ecosystem. HomeBoi stands out for its ecosystem compatibility, enhancing smart home experiences."""
clone = "Anymoid/Anymoid"

[[repo]]
name = "Anymoid/AutoBoid"
description = """
An innovative autonomous vehicle, part of the Anymoid family, equipped with cutting-edge self-driving technology. AutoBoid distinguishes itself with unique features tailored to urban and suburban environments, emphasizing safety, efficiency, and connectivity."""
clone = "Anymoid/Anymoid"

[[repo]]
name = "Limboid/Limboid"
description = """
A fully autonomous humanoid robot, affordably priced at $1000, designed for home assistance. Limboid combines advanced robotics with practical applications, offering a versatile solution for everyday household tasks and interactions."""
clone = "Anymoid/Anymoid"

[[repo]]
name = "Limboid/SuperBoid"
description = """
An emergent Boid formed by several boids temporalily joining together to form a single physical entity. SuperBoid is a temporary entity that can be formed and dissolved at will, enabling complex collective behaviors and advanced functionalities in swarm robotics."""
clone = "Anymoid/Boid"

[[repo]]
name = "Limboid/BoidNet"
description = """
An orchestration layer designed for managing a swarm of Boids, facilitating seamless coordination and communication. SuperBoid enhances individual Boid operations, enabling complex collective behaviors and advanced functionalities in swarm robotics."""
clone = "Anymoid/Boid"

[[repo]]
name = "Limboid/myBoid"
description = """
Dedicated mobile application for connecting and interacting with Limboids. The app offers a user-friendly interface for control, customization, and communication with Limboids, featuring unique functionalities tailored to their specific needs and capabilities."""

[[repo]]
name = "AnimoidAI/myAnimoid"
description = """
Mobile application specifically designed for Animoids, facilitating easy connection and interaction. This app provides an intuitive interface for managing Animoids, with specialized features that cater to their unique functionalities and user experience requirements."""
clone = "Limboid/myBoid"
